version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5231:5231"
    environment:
      - ASPNETCORE_URLS=http://+:5231
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:5231
